function res=cbiTranslateNiftiCodes(inp,cat)
% result=cbiTranslateNiftiCodes(inp,category)
% Converts a Nifti integer code into a cell array of strings corresponding to the #define in nifti.h,
% or vice versa. For integer code => string, if category is not specified, returns all possible options.
%
% category can be one of (case not important):
% 'DT', 'TYPE', 'INTENT', 'XFORM', 'UNITS', 'SLICE'
% 
% If an output is given but no input, returns the entire conversion table.

categories={'DT', 'TYPE', 'INTENT', 'XFORM', 'UNITS', 'SLICE'};
if (nargin==2)
    cat=upper(cat);
    if (~any(strcmp(cat,categories)))
        help(mfilename)
        return
    end
else
    cat=[];
end

niftiCodes=...
    {'DT_NONE' 0;...
     'DT_UNKNOWN' 0;...
     'DT_BINARY' 1;...
     'DT_UNSIGNED_CHAR' 2;...
     'DT_SIGNED_SHORT' 4;...
     'DT_SIGNED_INT' 8;...
     'DT_FLOAT' 16;...
     'DT_COMPLEX' 32;...
     'DT_DOUBLE' 64;...
     'DT_RGB' 128;...
     'DT_ALL' 255;...
     'DT_UINT8' 2;...
     'DT_INT16' 4;...
     'DT_INT32' 8;...
     'DT_FLOAT32' 16;...
     'DT_COMPLEX64' 32;...
     'DT_FLOAT64' 64;...
     'DT_RGB24' 128;...
     'DT_INT8' 256;...
     'DT_UINT16' 512;...
     'DT_UINT32' 768;...
     'DT_INT64' 1024;...
     'DT_UINT64' 1280;...
     'DT_FLOAT128' 1536;...
     'DT_COMPLEX128' 1792;...
     'DT_COMPLEX256' 2048;...
     'NIFTI_TYPE_UINT8' 2;...
     'NIFTI_TYPE_INT16' 4;...
     'NIFTI_TYPE_INT32' 8;...
     'NIFTI_TYPE_FLOAT32' 16;...
     'NIFTI_TYPE_COMPLEX64' 32;...
     'NIFTI_TYPE_FLOAT64' 64;...
     'NIFTI_TYPE_RGB24' 128;...
     'NIFTI_TYPE_INT8' 256;...
     'NIFTI_TYPE_UINT16' 512;...
     'NIFTI_TYPE_UINT32' 768;...
     'NIFTI_TYPE_INT64' 1024;...
     'NIFTI_TYPE_UINT64' 1280;...
     'NIFTI_TYPE_FLOAT128' 1536;...
     'NIFTI_TYPE_COMPLEX128' 1792;...
     'NIFTI_TYPE_COMPLEX256' 2048;...
     'NIFTI_INTENT_NONE' 0;...
     'NIFTI_INTENT_CORREL' 2;...
     'NIFTI_INTENT_TTEST' 3;...
     'NIFTI_INTENT_FTEST' 4;...
     'NIFTI_INTENT_ZSCORE' 5;...
     'NIFTI_INTENT_CHISQ' 6;...
     'NIFTI_INTENT_BETA' 7;...
     'NIFTI_INTENT_BINOM' 8;...
     'NIFTI_INTENT_GAMMA' 9;...
     'NIFTI_INTENT_POISSON' 10;...
     'NIFTI_INTENT_NORMAL' 11;...
     'NIFTI_INTENT_FTEST_NONC' 12;...
     'NIFTI_INTENT_CHISQ_NONC' 13;...
     'NIFTI_INTENT_LOGISTIC' 14;...
     'NIFTI_INTENT_LAPLACE' 15;...
     'NIFTI_INTENT_UNIFORM' 16;...
     'NIFTI_INTENT_TTEST_NONC' 17;...
     'NIFTI_INTENT_WEIBULL' 18;...
     'NIFTI_INTENT_CHI' 19;...
     'NIFTI_INTENT_INVGAUSS' 20;...
     'NIFTI_INTENT_EXTVAL' 21;...
     'NIFTI_INTENT_PVAL' 22;...
     'NIFTI_INTENT_LOGPVAL' 23;...
     'NIFTI_INTENT_LOG10PVAL' 24;...
     'NIFTI_FIRST_STATCODE' 2;...
     'NIFTI_LAST_STATCODE' 24;...
     'NIFTI_INTENT_ESTIMATE' 1001;...
     'NIFTI_INTENT_LABEL' 1002;...
     'NIFTI_INTENT_NEURONAME' 1003;...
     'NIFTI_INTENT_GENMATRIX' 1004;...
     'NIFTI_INTENT_SYMMATRIX' 1005;...
     'NIFTI_INTENT_DISPVECT' 1006;...
     'NIFTI_INTENT_VECTOR' 1007;...
     'NIFTI_INTENT_POINTSET' 1008;...
     'NIFTI_INTENT_TRIANGLE' 1009;...
     'NIFTI_INTENT_QUATERNION' 1010;...
     'NIFTI_INTENT_DIMLESS' 1011;...
     'NIFTI_XFORM_UNKNOWN' 0;...
     'NIFTI_XFORM_SCANNER_ANAT' 1;...
     'NIFTI_XFORM_ALIGNED_ANAT' 2;...
     'NIFTI_XFORM_TALAIRACH' 3;...
     'NIFTI_XFORM_MNI_152' 4;...
     'NIFTI_UNITS_UNKNOWN' 0;...
     'NIFTI_UNITS_METER' 1;...
     'NIFTI_UNITS_MM' 2;...
     'NIFTI_UNITS_MICRON' 3;...
     'NIFTI_UNITS_SEC' 8;...
     'NIFTI_UNITS_MSEC' 16;...
     'NIFTI_UNITS_USEC' 24;...
     'NIFTI_UNITS_HZ' 32;...
     'NIFTI_UNITS_PPM' 40;...
     'NIFTI_UNITS_RADS' 48;...
     'NIFTI_SLICE_UNKNOWN' 0;...
     'NIFTI_SLICE_SEQ_INC' 1;...
     'NIFTI_SLICE_SEQ_DEC' 2;...
     'NIFTI_SLICE_ALT_INC' 3;...
     'NIFTI_SLICE_ALT_DEC' 4};

if (nargin==0)
    if (nargout==1)
        res=niftiCodes;
    end
elseif (ischar(inp))
    % string to integer code
    [r,c]=find(strcmp(upper(inp),niftiCodes));
    res=niftiCodes{r,2};
elseif (isnumeric(inp))
    % integer code to string
    if (isempty(inp))
        res=niftiCodes(:,1);
    else
        r=find(inp==cell2mat(niftiCodes(:,2)));
        res=niftiCodes(r,1);
    end
    if (~isempty(cat))
        found=0;
        catres=[];
        for n=1:length(res)
            if (strfind(res{n},cat))
                catres=[catres;res(n)];
                found=1;
            end
        end
        if (~found)
            res={};
        else
            res=catres;
        end
    end
end
